import 'package:flutter/material.dart';

abstract final class LavenderScheme {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff7c4dff),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffeaddff),
    onPrimaryContainer: Color(0xff25005a),
    secondary: Color(0xff9a82db),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffe8ddff),
    onSecondaryContainer: Color(0xff22005d),
    tertiary: Color(0xffb388ff),
    onTertiary: Color(0xff331e4c),
    tertiaryContainer: Color(0xfff4eaff),
    onTertiaryContainer: Color(0xff331e4c),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff410002),
    surface: Color(0xfffbf8ff),
    onSurface: Color(0xff1d1b20),
    onSurfaceVariant: Color(0xff49454f),
    outline: Color(0xff7a757f),
    outlineVariant: Color(0xffcac4d0),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff322f35),
    onInverseSurface: Color(0xfff5eff7),
    inversePrimary: Color(0xffcfbcff),
    surfaceTint: Color(0xff7c4dff),
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xffcfbcff),
    onPrimary: Color(0xff3d0090),
    primaryContainer: Color(0xff5a00c7),
    onPrimaryContainer: Color(0xffeaddff),
    secondary: Color(0xffc9b8ff),
    onSecondary: Color(0xff31008a),
    secondaryContainer: Color(0xff4a00b8),
    onSecondaryContainer: Color(0xffe8ddff),
    tertiary: Color(0xffd9b8ff),
    onTertiary: Color(0xff44008a),
    tertiaryContainer: Color(0xff5e00b3),
    onTertiaryContainer: Color(0xfff4eaff),
    error: Color(0xffffb4ab),
    onError: Color(0xff690005),
    errorContainer: Color(0xff93000a),
    onErrorContainer: Color(0xffffb4ab),
    surface: Color(0xff141218),
    onSurface: Color(0xffe8e0e8),
    onSurfaceVariant: Color(0xffcac4d0),
    outline: Color(0xff948f99),
    outlineVariant: Color(0xff49454f),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffe8e0e8),
    onInverseSurface: Color(0xff322f35),
    inversePrimary: Color(0xff7c4dff),
    surfaceTint: Color(0xffcfbcff),
  );
}
