name: arch
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  cli_spin: ^1.0.1
  dart_tabulate: ^1.0.0
  interact: ^2.2.0
  process_run: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  change_app_package_name: ^1.3.0
  lints: ^3.0.0
  test: ^1.24.0
