import 'dart:convert';
import 'dart:io';
import 'package:archive/archive_io.dart';

void main() async {
  final templatesDir = Directory('lib/templates');
  if (!templatesDir.existsSync()) {
    print('Error: lib/templates directory not found.');
    exit(1);
  }

  print('Compressing lib/templates...');

  final encoder = ZipFileEncoder();
  final tempZipFile = File('temp_templates.zip');
  if (tempZipFile.existsSync()) {
    tempZipFile.deleteSync();
  }

  encoder.create(tempZipFile.path);
  await encoder.addDirectory(templatesDir, includeDirName: false);
  encoder.close();

  print('Reading zip bytes...');
  final zipBytes = await tempZipFile.readAsBytes();

  print('Writing to lib/src/generated/templates.g.dart...');
  final outputDir = Directory('lib/src/generated');
  if (!outputDir.existsSync()) {
    outputDir.createSync(recursive: true);
  }

  final outputFile = File('lib/src/generated/templates.g.dart');

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by tool/generate_templates.dart');
  buffer.writeln('');
  buffer.writeln('const List<int> templatesZipBytes = [');

  // Write bytes in lines to avoid massive single line
  for (var i = 0; i < zipBytes.length; i += 20) {
    var end = i + 20;
    if (end > zipBytes.length) end = zipBytes.length;
    buffer.write('  ');
    for (var j = i; j < end; j++) {
      buffer.write('${zipBytes[j]}, ');
    }
    buffer.writeln();
  }

  buffer.writeln('];');

  outputFile.writeAsStringSync(buffer.toString());

  // Cleanup
  tempZipFile.deleteSync();

  print('Done! Template size: ${zipBytes.length / 1024 / 1024} MB');
}

///CMD 
/*
dart run tool/generate_templates.dart   
dart compile exe bin/main.dart -o arch_cli && cp arch_cli ../piistech
*/