import 'country.dart';

final List<Country> countryList = [
  Country(
    name: 'United States',
    dialCode: '+1',
    phoneLength: 10,
    flag: '🇺🇸',
    isoCode: 'US',
  ),
  Country(
    name: 'United Kingdom',
    dialCode: '+44',
    phoneLength: 10,
    flag: '🇬🇧',
    isoCode: 'GB',
  ),
  Country(
    name: 'Canada',
    dialCode: '+1',
    phoneLength: 10,
    flag: '🇨🇦',
    isoCode: 'CA',
  ),
  Country(
    name: 'Germany',
    dialCode: '+49',
    phoneLength: 10,
    flag: '🇩🇪',
    isoCode: 'DE',
  ),
  Country(
    name: 'India',
    dialCode: '+91',
    phoneLength: 10,
    flag: '🇮🇳',
    isoCode: 'IN',
  ),
  Country(
    name: 'Australia',
    dialCode: '+61',
    phoneLength: 9,
    flag: '🇦🇺',
    isoCode: 'AU',
  ),
  Country(
    name: 'France',
    dialCode: '+33',
    phoneLength: 9,
    flag: '🇫🇷',
    isoCode: 'FR',
  ),
  Country(
    name: 'Brazil',
    dialCode: '+55',
    phoneLength: 11,
    flag: '🇧🇷',
    isoCode: 'BR',
  ),
  Country(
    name: 'South Africa',
    dialCode: '+27',
    phoneLength: 9,
    flag: '🇿🇦',
    isoCode: 'ZA',
  ),
  Country(
    name: 'Japan',
    dialCode: '+81',
    phoneLength: 10,
    flag: '🇯🇵',
    isoCode: 'JP',
  ),
  Country(
    name: 'Mexico',
    dialCode: '+52',
    phoneLength: 10,
    flag: '🇲🇽',
    isoCode: 'MX',
  ),
  Country(
    name: 'Italy',
    dialCode: '+39',
    phoneLength: 10,
    flag: '🇮🇹',
    isoCode: 'IT',
  ),
  Country(
    name: 'Spain',
    dialCode: '+34',
    phoneLength: 9,
    flag: '🇪🇸',
    isoCode: 'ES',
  ),
  Country(
    name: 'Russia',
    dialCode: '+7',
    phoneLength: 10,
    flag: '🇷🇺',
    isoCode: 'RU',
  ),
  Country(
    name: 'China',
    dialCode: '+86',
    phoneLength: 11,
    flag: '🇨🇳',
    isoCode: 'CN',
  ),
  Country(
    name: 'Nigeria',
    dialCode: '+234',
    phoneLength: 10,
    flag: '🇳🇬',
    isoCode: 'NG',
  ),
  Country(
    name: 'Argentina',
    dialCode: '+54',
    phoneLength: 10,
    flag: '🇦🇷',
    isoCode: 'AR',
  ),
  Country(
    name: 'Turkey',
    dialCode: '+90',
    phoneLength: 10,
    flag: '🇹🇷',
    isoCode: 'TR',
  ),
  Country(
    name: 'Egypt',
    dialCode: '+20',
    phoneLength: 10,
    flag: '🇪🇬',
    isoCode: 'EG',
  ),
  Country(
    name: 'Sweden',
    dialCode: '+46',
    phoneLength: 9,
    flag: '🇸🇪',
    isoCode: 'SE',
  ),
  Country(
    name: 'Norway',
    dialCode: '+47',
    phoneLength: 8,
    flag: '🇳🇴',
    isoCode: 'NO',
  ),
  Country(
    name: 'Netherlands',
    dialCode: '+31',
    phoneLength: 9,
    flag: '🇳🇱',
    isoCode: 'NL',
  ),
  Country(
    name: 'Switzerland',
    dialCode: '+41',
    phoneLength: 9,
    flag: '🇨🇭',
    isoCode: 'CH',
  ),
  Country(
    name: 'Belgium',
    dialCode: '+32',
    phoneLength: 9,
    flag: '🇧🇪',
    isoCode: 'BE',
  ),
  Country(
    name: 'South Korea',
    dialCode: '+82',
    phoneLength: 9,
    flag: '🇰🇷',
    isoCode: 'KR',
  ),
  Country(
    name: 'Indonesia',
    dialCode: '+62',
    phoneLength: 10,
    flag: '🇮🇩',
    isoCode: 'ID',
  ),
  Country(
    name: 'Saudi Arabia',
    dialCode: '+966',
    phoneLength: 9,
    flag: '🇸🇦',
    isoCode: 'SA',
  ),
  Country(
    name: 'Pakistan',
    dialCode: '+92',
    phoneLength: 10,
    flag: '🇵🇰',
    isoCode: 'PK',
  ),
  Country(
    name: 'Malaysia',
    dialCode: '+60',
    phoneLength: 10,
    flag: '🇲🇾',
    isoCode: 'MY',
  ),
  Country(
    name: 'Bangladesh',
    dialCode: '+880',
    phoneLength: 10,
    flag: '🇧🇩',
    isoCode: 'BD',
  ),
  Country(
    name: 'New Zealand',
    dialCode: '+64',
    phoneLength: 9,
    flag: '🇳🇿',
    isoCode: 'NZ',
  ),
  Country(
    name: 'Philippines',
    dialCode: '+63',
    phoneLength: 10,
    flag: '🇵🇭',
    isoCode: 'PH',
  ),
  Country(
    name: 'Vietnam',
    dialCode: '+84',
    phoneLength: 9,
    flag: '🇻🇳',
    isoCode: 'VN',
  ),
  Country(
    name: 'Thailand',
    dialCode: '+66',
    phoneLength: 9,
    flag: '🇹🇭',
    isoCode: 'TH',
  ),
  Country(
    name: 'Kenya',
    dialCode: '+254',
    phoneLength: 10,
    flag: '🇰🇪',
    isoCode: 'KE',
  ),
  Country(
    name: 'Ghana',
    dialCode: '+233',
    phoneLength: 9,
    flag: '🇬🇭',
    isoCode: 'GH',
  ),
  Country(
    name: 'Colombia',
    dialCode: '+57',
    phoneLength: 10,
    flag: '🇨🇴',
    isoCode: 'CO',
  ),
  Country(
    name: 'Chile',
    dialCode: '+56',
    phoneLength: 9,
    flag: '🇨🇱',
    isoCode: 'CL',
  ),
  Country(
    name: 'Peru',
    dialCode: '+51',
    phoneLength: 9,
    flag: '🇵🇪',
    isoCode: 'PE',
  ),
  Country(
    name: 'Poland',
    dialCode: '+48',
    phoneLength: 9,
    flag: '🇵🇱',
    isoCode: 'PL',
  ),
  Country(
    name: 'Portugal',
    dialCode: '+351',
    phoneLength: 9,
    flag: '🇵🇹',
    isoCode: 'PT',
  ),
  Country(
    name: 'Austria',
    dialCode: '+43',
    phoneLength: 10,
    flag: '🇦🇹',
    isoCode: 'AT',
  ),
  Country(
    name: 'Denmark',
    dialCode: '+45',
    phoneLength: 8,
    flag: '🇩🇰',
    isoCode: 'DK',
  ),
  Country(
    name: 'Finland',
    dialCode: '+358',
    phoneLength: 9,
    flag: '🇫🇮',
    isoCode: 'FI',
  ),
  Country(
    name: 'Ukraine',
    dialCode: '+380',
    phoneLength: 9,
    flag: '🇺🇦',
    isoCode: 'UA',
  ),
  Country(
    name: 'Ireland',
    dialCode: '+353',
    phoneLength: 9,
    flag: '🇮🇪',
    isoCode: 'IE',
  ),
  Country(
    name: 'Greece',
    dialCode: '+30',
    phoneLength: 10,
    flag: '🇬🇷',
    isoCode: 'GR',
  ),
  Country(
    name: 'Czech Republic',
    dialCode: '+420',
    phoneLength: 9,
    flag: '🇨🇿',
    isoCode: 'CZ',
  ),
  Country(
    name: 'Romania',
    dialCode: '+40',
    phoneLength: 9,
    flag: '🇷🇴',
    isoCode: 'RO',
  ),
  Country(
    name: 'Hungary',
    dialCode: '+36',
    phoneLength: 9,
    flag: '🇭🇺',
    isoCode: 'HU',
  ),
  Country(
    name: 'Slovakia',
    dialCode: '+421',
    phoneLength: 9,
    flag: '🇸🇰',
    isoCode: 'SK',
  ),
  Country(
    name: 'Israel',
    dialCode: '+972',
    phoneLength: 9,
    flag: '🇮🇱',
    isoCode: 'IL',
  ),
  Country(
    name: 'Iran',
    dialCode: '+98',
    phoneLength: 10,
    flag: '🇮🇷',
    isoCode: 'IR',
  ),
  Country(
    name: 'Morocco',
    dialCode: '+212',
    phoneLength: 9,
    flag: '🇲🇦',
    isoCode: 'MA',
  ),
  Country(
    name: 'Algeria',
    dialCode: '+213',
    phoneLength: 9,
    flag: '🇩🇿',
    isoCode: 'DZ',
  ),
  Country(
    name: 'Sudan',
    dialCode: '+249',
    phoneLength: 9,
    flag: '🇸🇩',
    isoCode: 'SD',
  ),
  Country(
    name: 'Ethiopia',
    dialCode: '+251',
    phoneLength: 9,
    flag: '🇪🇹',
    isoCode: 'ET',
  ),
  Country(
    name: 'Tunisia',
    dialCode: '+216',
    phoneLength: 8,
    flag: '🇹🇳',
    isoCode: 'TN',
  ),
  Country(
    name: 'Uganda',
    dialCode: '+256',
    phoneLength: 9,
    flag: '🇺🇬',
    isoCode: 'UG',
  ),
  Country(
    name: 'Tanzania',
    dialCode: '+255',
    phoneLength: 9,
    flag: '🇹🇿',
    isoCode: 'TZ',
  ),
  Country(
    name: 'Zimbabwe',
    dialCode: '+263',
    phoneLength: 9,
    flag: '🇿🇼',
    isoCode: 'ZW',
  ),
  Country(
    name: 'Myanmar',
    dialCode: '+95',
    phoneLength: 9,
    flag: '🇲🇲',
    isoCode: 'MM',
  ),
  Country(
    name: 'Sri Lanka',
    dialCode: '+94',
    phoneLength: 9,
    flag: '🇱🇰',
    isoCode: 'LK',
  ),
  Country(
    name: 'Maldives',
    dialCode: '+960',
    phoneLength: 7,
    flag: '🇲🇻',
    isoCode: 'MV',
  ),
  Country(
    name: 'Nepal',
    dialCode: '+977',
    phoneLength: 9,
    flag: '🇳🇵',
    isoCode: 'NP',
  ),
  Country(
    name: 'Kazakhstan',
    dialCode: '+7',
    phoneLength: 10,
    flag: '🇰🇿',
    isoCode: 'KZ',
  ),
  Country(
    name: 'Uzbekistan',
    dialCode: '+998',
    phoneLength: 9,
    flag: '🇺🇿',
    isoCode: 'UZ',
  ),
];
